/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (100000) [MemberId]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[DOB]
      ,[Age]
      ,[Gender]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[City]
      ,[State]
      ,[ZipCode]
      ,[DiagnosesDesc]
      ,[ProcedureDesc]
      ,[Medications]
      ,[Facility]
      ,[FacilityAddress1]
      ,[FacilityAddress2]
      ,[FacilityCity]
      ,[FacilityState]
      ,[FacilityZipCode]
      ,[AdmissionType]
      ,[AdmitDate]
      ,[DischargeDate]
      ,[DischargeDisposition]
      ,[Priority]
      ,[BehavorialHealth]
      ,[ReAdmissions]
      ,[ERVisits]
      ,[PolyPharmacy]
      ,[ChronicConditions]
      ,[fileName]
	  ,SUBSTRING(fileName, 15,4) as fileyear
  FROM [RAE4].[dbo].[InpatientDataEQHealth]
  where SUBSTRING(fileName, 15,4) = '2020'
  ORDER BY fileName DESC

